dashboard:
  path: /
  controller: \Dashboard\Controller\DashboardController
  action: index
  methods:
    - GET

category:
  path: /category
  controller: \Category\Controller\CategoryController
  action: index
  methods:
    - GET

category_create:
  path: /category/add
  controller: \Category\Controller\CategoryController
  action: create
  methods:
    - GET
    - POST

category_update:
  path: /category/edit/{id}
  controller: \Category\Controller\CategoryController
  action: update
  methods:
    - GET
    - POST

category_delete:
  path: /category/remove/{id}
  controller: \Category\Controller\CategoryController
  action: delete
  methods:
    - GET

product:
  path: /product
  controller: \Product\Controller\ProductController
  action: index
  methods:
    - GET

product_create:
  path: /product/add
  controller: \Product\Controller\ProductController
  action: create
  methods:
    - GET
    - POST

product_update:
  path: /product/edit/{id}
  controller: \Product\Controller\ProductController
  action: update
  methods:
    - GET
    - POST

product_delete:
  path: /product/remove/{id}
  controller: \Product\Controller\ProductController
  action: delete
  methods:
    - GET