dashboard:
  path: /
  controller: \Dashboard\Controller\DashboardController
  action: index
  methods:
    - GET

category_list:
  path: /category
  controller: \Category\Controller\CategoryController
  action: list
  methods:
    - GET

category_new:
  path: /category/new
  controller: \Category\Controller\CategoryController
  action: new
  methods:
    - GET
    - POST

product_list:
  path: /product
  controller: \Product\Controller\ProductController
  action: list
  methods:
    - GET